SistemaINADE2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')), # Incluye las URLs de la aplicación 'accounts'
]

accounts/urls.py
from django.urls import path
from accounts.vistas import views_usuarios, views_prospectos, views_empresas_contactos, views_autenticacion, views_home, views_cotizaciones, views_servicios

urlpatterns = [
    path('', views_autenticacion.dashboard, name='dashboard'),
    path('login/', views_autenticacion.login_view, name='login'),
    path('logout/', views_autenticacion.logout_view, name='logout'),
    path('mostrar_CustomUser/', views_autenticacion.mostrar_CustomUser,name='mostrar_CustomUser'),
    
    path('home/', views_home.home, name='home'),
    
    path('usuarios/',views_usuarios.usuario_list,name='usuario_list'),
    path('usuarios/new/',views_usuarios.usuario_create,name='usuario_create'),
    path('usuario/<username>/delete/',views_usuarios.usuario_delete,name='usuario_delete'),
    path('usuario/<username>/edit/', views_usuarios.usuario_update, name='usuario_edit'),
    path('usuario/<username>/edit2/',views_usuarios.usuario_update2, name='usuario_edit2'),
    
    path('prospectos/',views_prospectos.prospecto_list, name='prospecto_list'),
    path('prospecto/new/',views_prospectos.prospecto_new, name='prospecto_new'),
    path('prospecto/create/',views_prospectos.prospecto_create, name='prospecto_create'),
    path('prospecto/<int:pk>/edit/',views_prospectos.prospecto_edit,name='prospecto_edit'),
    path('prospecto/<int:pk>/update/',views_prospectos.prospecto_update,name='prospecto_update'),
    path('prospecto/<int:pk>/delete/',views_prospectos.prospecto_delete, name='prospecto_delete'),
    
    path('empresas-contactos/',views_empresas_contactos.empresa_cont_list, name='empresas_cont_list'),
    path('empresas/<int:pk>/edit/',views_empresas_contactos.empresa_edit, name='empresa_edit'),
    path('empresas/<int:pk>/update',views_empresas_contactos.empresa_update,name='empresa_update'),
    path('empresas/<int:pk>/delete/',views_empresas_contactos.empresa_delete, name='empresa_delete'),
    path('contacto/<int:pk>/edit/',views_empresas_contactos.contacto_edit,name='contacto_edit'),
    path('contacto/<int:pk>/update/',views_empresas_contactos.contacto_update,name='contacto_update'),
    path('contacto/<int:pk>/delete/',views_empresas_contactos.contacto_delete, name='contacto_delete'),
    
    path('metodo/',views_servicios.metodos_list,name='metodos_list'),
    path('metodo/new/',views_servicios.metodo_create,name='metodo_create'),
    path('metodo/<int:pk>/delete/',views_servicios.metodo_delete,name='metodo_delete'),
    
    path('servicios/',views_servicios.servicios_list,name='servicios_list'),
    path('servicio/new/',views_servicios.servicio_new,name='servicio_new'),
    path('servicio/create/', views_servicios.servicio_create, name='servicio_create'),
    path('servicio/<int:pk>/edit/',views_servicios.servicio_edit,name='servicio_edit'),
    path('servicio/<int:pk>/update/', views_servicios.servicio_update, name='servicio_update'),
    path('servicio/<int:pk>/delete/',views_servicios.servicio_delete,name='servicio_delete'),
    
    path('cotizaciones/', views_cotizaciones.cotizaciones_list, name='cotizaciones_list'),
    path('cotizacion/new', views_cotizaciones.cotizacion_new, name='cotizacion_new'),
    path('cotizacion/register/', views_cotizaciones.cotizacion_register, name='cotizacion_register')

    
    
    # Define otras rutas según las vistas que hayas definido
]

accounts/models.py
from datetime import date
from django.db import models
from django.contrib.auth.models import  BaseUserManager, AbstractUser
# Opcional: Agregar señales para manejar el cálculo del subtotal, IVA y total automáticamente cuando se guarden los objetos CotizacionConcepto.
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver

# En accounts/models.py, define el modelo de usuario personalizado que tenga campos adicionales para los diferentes roles.

# MODELO PARA USUARIOS ADMINISTRADORES
class CustomUserManager(BaseUserManager):
    
    def create_user(self, username, email, password=None, first_name=None, last_name=None, celular=None, rol=None, **extra_fields):
        
        if not username:
            raise ValueError('El usuario debe tener un nombre de usuario.')
        if not email:
            raise ValueError('El usuario debe tener un correo electrónico.')
        
        email = self.normalize_email(email)
        
        user = self.model(username=username, email=email, first_name=first_name, last_name=last_name, celular=celular, rol=rol, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        
        return user
    
    def create_superuser(self, username, email, password=None, **extra_fields):
        
        # Campos opcionales para crear super usuario 
        extra_fields.setdefault('first_name', 'Admin')
        extra_fields.setdefault('last_name', 'User')
        extra_fields.setdefault('celular', '')
        extra_fields.setdefault('rol', 'admin')
        
        user = self.create_user(
            username=username,
            email=email,
            password=password,
            **extra_fields
        )
        
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

# MODELO PARA CLIENTES 
class CustomUser(AbstractUser):
    
    # username = models.CharField(max_length=150, unique=True)
    # nombre = models.CharField(max_length=100)
    # apellido = models.CharField(max_length=100)
    # correo = models.EmailField(unique=True)
    # ESTOS YA ESTAN AGREGADOS EN LA TABLA PREDETERMINADA DE USER
    
    celular = models.CharField(max_length=15, blank=True, null=True)
    
    AREA_CHOICES = [
        ('admin', 'Administrador'),
        ('coordinador', 'Coordinador'),
        ('muestras', 'Muestras'),
        ('informes', 'Informes'),
        ('laboratorio', 'Laboratorio'),
        ('calidad', 'Calidad')
    ]
    rol = models.CharField(max_length=20, choices=AREA_CHOICES, blank=True, null=True)

    objects = CustomUserManager()

    def __str__(self):
        return self.username

#----------------------------------------------------
# MODELO PARA PROSPECTOS
#----------------------------------------------------

# MODELO PARA DIRECCION
class Direccion(models.Model):
    id = models.AutoField(primary_key=True)
    calle = models.CharField(max_length=50, null=False, blank=False)
    numero = models.CharField(max_length=50, null=False, blank=False)
    colonia = models.CharField(max_length=100, null=False, blank=False)
    ciudad = models.CharField(max_length=100, null=False, blank=False)
    codigo = models.CharField(max_length=6, null=False, blank=False)
    estado = models.CharField(max_length=100, null=False, blank=False)
    
    def __str__(self):
        return f"{self.calle} {self.numero}, {self.colonia}, {self.ciudad}, {self.estado} {self.codigo}"

# MODELO PARA EMPRESA
class Empresa(models.Model):
    id = models.AutoField(primary_key=True)
    nombre_empresa = models.CharField(max_length=100, null=False, blank=False)
    rfc = models.CharField(max_length=50, null=False, blank=True)
    direccion = models.OneToOneField(Direccion, on_delete=models.CASCADE, null=True, blank=True)
    tipo_moneda = [
        ('mxn', 'MXN - Moneda Nacional Mexicana'),
        ('usd', 'USD - Dolar Estadunidense')
    ]
    moneda = models.CharField(max_length=10, choices=tipo_moneda, blank=True, null=True)
    condiciones_pago = models.CharField(max_length=200, null=False, blank=True, default='15')

# MODELO DE TITULOS
class Titulo(models.Model):
    id = models.AutoField(primary_key=True)
    titulo = models.CharField(max_length=50, null=False, blank=False)
    abreviatura = models.CharField(max_length=10, null=False, blank=False)
    
    def __str__(self):
        return self.titulo

# MODELO PARA INFORMACION DE CONTACTO
class InformacionContacto(models.Model):
    id = models.AutoField(primary_key=True)
    correo_electronico = models.EmailField(null=False, blank=False)
    telefono = models.CharField(max_length=120, blank=True)  # Agregando blank=True
    celular = models.CharField(max_length=20, blank=True)  # Agregando blank=True
    fax = models.CharField(max_length=20, blank=True)  # Agregando blank=True
    
    def __str__(self):
        return f"{self.correo_electronico} - {self.telefono} / {self.celular}"

# MODELO BASE PARA PERSONA
class Persona(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50, null=False, blank=False)
    apellidos = models.CharField(max_length=100, null=False, blank=False)
    titulo = models.ForeignKey(Titulo, on_delete=models.SET_NULL, null=True, blank=True)  # null=True
    informacion_contacto = models.ForeignKey(InformacionContacto, on_delete=models.SET_NULL, null=True, blank=True)  # null=True
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.nombre} {self.apellidos}"

# MODELO PARA PROSPECTO
class Prospecto(models.Model):
    persona = models.OneToOneField(Persona, on_delete=models.CASCADE, related_name='prospecto')

# MODELO PARA CLIENTE
class Cliente(models.Model):
    persona = models.OneToOneField(Persona, on_delete=models.CASCADE, related_name='cliente')

#----------------------------------------------------
# MODELO PARA CONCEPTOS
#----------------------------------------------------

# MODELO PARA METODO
class Metodo(models.Model):
    nombre = models.CharField(max_length=100)# REPRESENNTA EL METODO
    leyenda = models.TextField(default="Leyenda predeterminada")# MUESTRA UNA DESCRIPCION DE LA NORMA
    def __str__(self):
        return self.nombre

# MODELO PARA SERVICIO
class Servicio(models.Model):
    servicio = models.CharField(max_length=50)# REPRESENTA EL NOMBRE DEL SERVICIO
    descripcion = models.TextField()#MUESTRA UNA DESCRIPCION DEL SERVICIO
    precio_sugerido = models.DecimalField(max_digits=10, decimal_places=2)
    metodo = models.ForeignKey(Metodo, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.nombre_concepto
    
# MODELO PARA CONCEPTO
class Concepto(models.Model):
    nombre_concepto = models.ForeignKey(Servicio, on_delete=models.CASCADE)
    cantidad_servicios = models.IntegerField()
    notas = models.TextField()

    def total(self):
        return self.cantidad_servicios * self.servicio.precio_sugerido

    def __str__(self):
        return f'{self.servicio.nombre_concepto} - {self.cantidad_servicios}'
    
#----------------------------------------------------
# MODELO PARA COTIZACIONES
#----------------------------------------------------

# MODELO DE COTIZACION
class Cotizacion(models.Model):
    fecha_solicitada = models.DateField()
    fecha_caducidad = models.DateField()
    metodo_pago = models.CharField(max_length=100)
    tasa_iva = models.DecimalField(max_digits=4, decimal_places=2, default=0.16)
    notas = models.TextField(blank=True, null=True)
    correoss_adicionales = models.TextField(blank=True, null=True, help_text=("Lista de correos adicionales separados por comas"))
    subtotal = models.DecimalField(max_digits=10, decimal_places=2)
    iva = models.DecimalField(max_digits=10,decimal_places=2)
    total = models.DecimalField(max_digits=10, decimal_places=2)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE,blank=True, null=True)
    prospecto = models.ForeignKey(Prospecto, on_delete=models.CASCADE, blank=True, null=True)
    id_personalizado = models.CharField(max_length=20, unique=True)
    
    def save(self, *args, **kwargs):
        if not self.id_personalizado:
            today = date.today()
            last_cotizacion = Cotizacion.objects.filter(fecha_solicitud=today).count() + 1
            self.id_personalizado = f"{today.strftime('%y%m%d')}-{last_cotizacion:02d}"
        super().save(*args, **kwargs)

    def __str__(self):
        return self.id_personalizado
     
# MODELO DE COTIZACION CONCEPTO
class CotizacionConcepto(models.Model):
    cotizacion = models.ForeignKey(Cotizacion, on_delete=models.CASCADE)
    concepto = models.ForeignKey(Concepto, on_delete=models.CASCADE)
    cantidad = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.cotizacion.id_personalizado} - {self.concepto.nombre_concepto.servicio}"

@receiver(post_save, sender=CotizacionConcepto)
@receiver(post_delete, sender=CotizacionConcepto)

def actualizar_totales(sender, instance, **kwargs):
    cotizacion = instance.cotizacion
    conceptos = CotizacionConcepto.objects.filter(cotizacion=cotizacion)
    subtotal = sum(concepto.concepto.total() for concepto in conceptos)
    iva = subtotal * cotizacion.tasa_iva
    total = subtotal + iva
    Cotizacion.objects.filter(id=cotizacion.id).update(subtotal=subtotal, iva=iva, total=total)
    
    
# Cotizacion: Modelo para las cotizaciones, con campos para las fechas, método de pago, tasa de IVA, notas, correos adicionales, subtotal, IVA, total, cliente (opcional), prospecto, e ID personalizado.
# CotizacionConcepto: Modelo para asociar conceptos a una cotización, con una relación many-to-many entre Cotizacion y Concepto y un campo para la cantidad.

accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from .models import CustomUser
from django.contrib import messages
from django.http import JsonResponse

# Resto de tu código de vistas aquí...

accounts/templates/accounts/servicios/dashboard_admin_servicios.html
{% extends 'accounts/base_dashboard.html' %}
{% load static %}
{% block title %}Servicios{% endblock %}
{% block header %}Servicios{% endblock %}
{% block content %}

<!-- MENSAJES DE ALERTA -->
{% if messages %}
{% for message in messages %}
    <div class="alert alert-info alert-dismissible fade show" role="alert">
        <strong>{{ message }}</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% endfor %}
{% endif %}

<!-- CONTENEDOR SERVICIOS -->
<div class="container mt-4">
    <!-- SECCION DE TITULO ENCABEZANDO SERVICIOS -->
    <div class="row">
        <div class="col">
            <h1 class="text-center">Servicios</h1>
             <hr />
        </div>
    </div>

    <!-- BOTON NUEVO -->
    <div class="row mb-3">
        <div class="col text-right">
            <a href="{% url 'servicio_new' %}" class="btn btn-primary">Nuevo</a>
        </div>
    </div>

    <!-- TABLA -->
    <div class="row">
        <div class="col" style="position: relative; z-index: 1;">
            <table class="table table-hover table-light table-bordered" >
                <!-- ENCABEZADO DE TABLA -->
                <thead class="thead-dark">
                    <tr>
                        <th>#</th>
                        <th>Nombre</th>
                        <th>Metodo</th>
                        <th>Descripcion</th>
                        <th>Precio sugerido</th>
                        
                        <th colspan="2">Opciones</th>
                    </tr>
                </thead>
    
                <!-- CUERPO DE TABLA -->
                <tbody>
                    {% for s in servicios %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ s.servicio }}</td>
                        <td>{{ s.metodo.nombre }}</td>
                        <td>{{ s.descripcion }}</td>
                        <td>{{ s.precio_sugerido }}</td>
                        <td>
                            <a href="{% url 'servicio_edit' s.id %}" class="btn btn-info btn-sm">Editar</a>
                            
                        </td>
                        <td>
                            <a href="{% url 'servicio_delete' s.id %}" class="btn btn-danger btn-sm">Eliminar</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

</div>

{% endblock %}

<!-- Mensajes de alertas -->
<script src="{% static 'js/alertas.js' %}"></script>
<!-- Incluye Bootstrap CSS -->
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

<!-- Incluye jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!-- Incluye Bootstrap JS -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<!-- Incluye tu archivo JS personalizado -->
<script src="{% static 'js/alertas.js' %}"></script>

accounts/templates/accounts/servicios/servicios_crear.html
{% extends 'accounts/base_dashboard.html' %}
{% load static %}
{% block title %}Crear Servicio{% endblock %}
{% block header %}Crear Servicio{% endblock %}
{% block content %}
 <!-- TITULO Y FORMULARIO -->
<div class="container mt-4">
    <h1 class="text-center">Nuevo servicio</h1>
    <hr />
    <!-- FORMULARIO -->
    <div class="d-flex justify-content-center">
        <form action="{% url 'servicio_create' %}" method="post" class="col-md-7">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-12">
                    <h2>Método</h2>
                    <div class="form-group">
                        <label for="metodo_select">Método:</label>
                        <select id="metodo_select" class="form-control" name="metodo">
                            <option value="" selected>Seleccione un método</option>
                            {% for metodo in metodos %}
                            <option value="{{ metodo.id }}">{{ metodo.nombre }}</option>
                            {% endfor %}
                            <option value="nuevo">Crear nuevo método</option>
                        </select>
                    </div>
                    <div id="nuevo_metodo_form" style="display: none;">
                        {{ metodo_form.as_p }}
                    </div>
                    <h2>Servicio</h2>
                    {{ servicio_form.as_p }}
                </div>
            </div>

            <!-- BOTONES ACEPTAR CANDELAR-->
            <div class="form-group text-right">
                <input type="submit" class="btn btn-success" value="Registrar">
                <input type="button" class="btn btn-danger" value="Cancelar" onclick="location.href='{% url 'prospecto_list' %}'">
            </div>
        </form>
    </div>
</div>

 <!-- SCRIPTS -->
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var metodoSelect = document.getElementById('metodo_select');
        var nuevoMetodoForm = document.getElementById('nuevo_metodo_form');
        var nombreInput = document.querySelector('#nuevo_metodo_form #id_nombre');

        metodoSelect.addEventListener('change', function() {
            if (this.value === 'nuevo') {
                nuevoMetodoForm.style.display = 'block';
                if (nombreInput) {
                    nombreInput.removeAttribute('disabled');
                    nombreInput.setAttribute('required', 'required');
                }
            } else {
                nuevoMetodoForm.style.display = 'none';
                if (nombreInput) {
                    nombreInput.setAttribute('disabled', 'disabled');
                    nombreInput.removeAttribute('required');
                }
            }
        });
    });
</script>

{% endblock %}

accounts/templates/accounts/servicios/servicios_editar.html
{% extends 'accounts/base_dashboard.html' %}

{% load static %}

{% block title %}Gestión de servicios{% endblock %}
{% block header %}Gestión de servicios{% endblock %}

{% block content %}
<div class="container mt-4">
    <h1 class="text-center">Editar servicio</h1>
    <hr />
    <!-- FORMULARIO -->
    <div class="d-flex justify-content-center">
        <form action="{% url 'servicio_update' servicio.id %}" method="post" class="col-md-7" id="servicioForm">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-12">
                    <h2>Método</h2>
                    <div class="form-group">
                        <label for="metodo_select">Método:</label>
                        <select id="metodo_select" class="form-control" name="metodo">
                            <option value="" selected>Seleccione un método</option>
                            {% for metodo in metodos %}
                            <option value="{{ metodo.id }}" {% if servicio.metodo.id == metodo.id %}selected{% endif %}>{{ metodo.nombre }}</option>
                            {% endfor %}
                            <option value="nuevo">Crear nuevo método</option>
                        </select>
                    </div>
                    <div id="nuevo_metodo_form" style="display: none;">
                        {{ metodo_form.as_p }}
                    </div>
                    <h2>Servicio</h2>
                    {{ servicio_form.as_p }}
                </div>
            </div>

            <div class="form-group text-right">
                <input type="submit" class="btn btn-success" value="Registrar">
                <input type="button" class="btn btn-danger" value="Cancelar" onclick="location.href='{% url 'servicios_list' %}'">
            </div>
        </form>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        var metodoSelect = document.getElementById('metodo_select');
        var nuevoMetodoForm = document.getElementById('nuevo_metodo_form');
        var nombreInput = document.querySelector('#nuevo_metodo_form #id_nombre');
        var leyendaInput = document.querySelector('#nuevo_metodo_form #id_leyenda');

        function toggleNuevoMetodoForm() {
            if (metodoSelect.value === 'nuevo') {
                nuevoMetodoForm.style.display = 'block';
                if (nombreInput) {
                    nombreInput.removeAttribute('disabled');
                    nombreInput.setAttribute('required', 'required');
                }
                if (leyendaInput) {
                    leyendaInput.removeAttribute('disabled');
                    leyendaInput.setAttribute('required', 'required');
                }
            } else {
                nuevoMetodoForm.style.display = 'none';
                if (nombreInput) {
                    nombreInput.setAttribute('disabled', 'disabled');
                    nombreInput.removeAttribute('required');
                }
                if (leyendaInput) {
                    leyendaInput.setAttribute('disabled', 'disabled');
                    leyendaInput.removeAttribute('required');
                }
            }
        }

        metodoSelect.addEventListener('change', toggleNuevoMetodoForm);
        toggleNuevoMetodoForm(); // Para configurar correctamente al cargar la página
    });
</script>

{% endblock %}

accounts/templates/accounts/servicios/servicios_metodos.html
{% extends 'accounts/base_dashboard.html' %}

{% load static %}

{% block title %}Gestión de clientes{% endblock %}
{% block header %}Gestión de clientes{% endblock %}

{% block content %}

<!-- MENSAJES DE ALERTA -->
{% if messages %}
{% for message in messages %}
    <div class="alert alert-info alert-dismissible fade show" role="alert">
        <strong>{{ message }}</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% endfor %}
{% endif %}

<!-- CONTENEDOR DE METODOS -->
<div class="container mt-4">
    <h1 class="text-center">Métodos existentes</h1>
    <hr />
    
    <div class="row">
        <!-- FORMULARIO -->
        <div class="col-md-3">
            <h2>Crear nuevo método</h2>

            <form action="{% url 'metodo_create' %}" method="POST">    
               
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_nombre">Nombre del Metodo</label>
                    <input type="text" name="nombre" class="form-control" maxlength="100" id="id_nombre"  />
                </div>
                <div class="form-group">
                    <label for="id_leyenda">Leyenda</label>
                    <textarea name="leyenda" class="form-control" rows="4" id="id_leyenda" ></textarea>
                </div>
                <input type="submit" class="btn btn-success" value="Registrar" />
            </form>
        </div>

        <!-- SECCIÓN DE LISTADO DE MÉTODOS -->
        <div class="col-md-9">
            <h2>Lista de métodos</h2>
            <table class="table table-hover table-light table-bordered">
                <thead class="thead-dark">
                    <tr>
                        <th>#</th>
                        <th>Método</th>
                        <th>Leyenda</th>
                        <th colspan="1">Opciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for m in metodos %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ m.nombre }}</td>
                        <td>{{ m.leyenda }}</td>
                        <td><a href="{% url 'metodo_delete' m.id %}" class="btn btn-danger btn-sm">Eliminar</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>


{% endblock %}

<script src="{% static 'js/alertas.js' %}"></script>
<!-- Incluye Bootstrap CSS -->
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

<!-- Incluye jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!-- Incluye Bootstrap JS -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<!-- Incluye tu archivo JS personalizado -->
<script src="{% static 'js/alertas.js' %}"></script>